"""
管理台菜单与按钮权限种子。

本文件以用户提供的历史 `authorities` 数据为参考来源，尽量保持：
1. 菜单标题、路径、图标名称与原管理后台一致；
2. 隐藏路由的 `active`、内嵌页 `routePath` 等元信息可被前端直接消费；
3. 在保留历史菜单结构的同时，补充当前前端已接入的按钮权限节点。
"""

from typing import Any


def _merge_meta(
    lang: tuple[str, str] | None = None,
    *,
    active: str | None = None,
    badge: dict[str, Any] | None = None,
    hide_footer: bool | None = None,
) -> dict[str, Any]:
    meta: dict[str, Any] = {}
    if lang:
        meta["lang"] = {"zh_TW": lang[0], "en": lang[1]}
    if active:
        meta["active"] = active
    if badge:
        meta["props"] = {"badge": badge}
    if hide_footer is not None:
        meta["hideFooter"] = hide_footer
    return meta


def _menu(
    key: str,
    parent_key: str | None,
    title: str,
    path: str | None,
    component: str | None,
    sort_number: int,
    authority: str | None,
    *,
    icon: str | None = None,
    hide: int = 0,
    meta: dict[str, Any] | None = None,
    open_type: int = 0,
    redirect: str | None = None,
    menu_type: int = 0,
) -> dict[str, Any]:
    return {
        "key": key,
        "parent_key": parent_key,
        "title": title,
        "path": path,
        "component": component,
        "menu_type": menu_type,
        "sort_number": sort_number,
        "authority": authority,
        "icon": icon,
        "hide": hide,
        "meta": meta or {},
        "open_type": open_type,
        "redirect": redirect,
    }


def _directory(
    key: str,
    parent_key: str | None,
    title: str,
    path: str,
    sort_number: int,
    *,
    icon: str,
    authority: str | None = None,
    meta: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return _menu(
        key,
        parent_key,
        title,
        path,
        None,
        sort_number,
        authority,
        icon=icon,
        meta=meta,
    )


def _page(
    key: str,
    parent_key: str | None,
    title: str,
    path: str,
    component: str,
    sort_number: int,
    *,
    icon: str | None = None,
    authority: str | None = None,
    hide: int = 0,
    meta: dict[str, Any] | None = None,
    open_type: int = 0,
) -> dict[str, Any]:
    return _menu(
        key,
        parent_key,
        title,
        path,
        component,
        sort_number,
        authority,
        icon=icon,
        hide=hide,
        meta=meta,
        open_type=open_type,
    )


def _hidden_page(
    key: str,
    parent_key: str,
    title: str,
    path: str,
    component: str,
    sort_number: int,
    *,
    icon: str | None = "IconProLinkOutlined",
    authority: str | None = None,
    meta: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return _page(
        key,
        parent_key,
        title,
        path,
        component,
        sort_number,
        icon=icon,
        authority=authority,
        hide=1,
        meta=meta,
    )


def _button(
    key: str,
    parent_key: str,
    title: str,
    authority: str,
    sort_number: int,
) -> dict[str, Any]:
    return _menu(
        key,
        parent_key,
        title,
        None,
        None,
        sort_number,
        authority,
        hide=1,
        menu_type=1,
    )


DASHBOARD_SEED_MENUS = [
    _page(
        "dashboard-overview",
        None,
        "总览",
        "/dashboard/monitor",
        "/dashboard/monitor",
        0,
        icon="IconProHomeOutlined",
        meta=_merge_meta(("總覽", "Overview")),
    ),
]


BUSINESS_SEED_MENUS = [
    _page(
        "task-management",
        None,
        "任务管理",
        "/task/management",
        "/task/management",
        1,
        icon="IconProCalendarOutlined",
    ),
    _hidden_page(
        "task-create",
        "task-management",
        "新建巡查任务",
        "/task/management/create",
        "/task/management/create",
        101,
        icon="IconProAppstoreAddOutlined",
        meta=_merge_meta(("新建巡查任務", "Create Patrol Task"), active="/task/management"),
    ),
    _hidden_page(
        "task-detail",
        "task-management",
        "巡查任务详情",
        "/task/management/detail",
        "/task/management/detail",
        102,
        icon="IconProLinkOutlined",
        meta=_merge_meta(("巡查任務詳情", "Patrol Task Detail"), active="/task/management"),
    ),
    _hidden_page(
        "task-edit",
        "task-management",
        "编辑巡查任务",
        "/task/management/edit",
        "/task/management/edit",
        103,
        icon="IconProEditOutlined",
        meta=_merge_meta(("編輯巡查任務", "Edit Patrol Task"), active="/task/management"),
    ),
    _page(
        "task-schedule",
        None,
        "任务调度",
        "/task/schedule",
        "/task/schedule",
        2,
        icon="IconProControlOutlined",
    ),
    _page(
        "patrol-map",
        None,
        "巡查地图",
        "/patrol/map",
        "/patrol/map",
        3,
        icon="IconProCompassOutlined",
    ),
    _page(
        "event-workorder",
        None,
        "事件工单",
        "/event/workorder",
        "/event/workorder",
        4,
        icon="IconProWarningOutlined",
    ),
    _page(
        "event-push-log",
        None,
        "推送日志",
        "/event/push-log",
        "/event/push-log",
        5,
        icon="IconProLogOutlined",
    ),
    _page(
        "document-center",
        None,
        "文书中心",
        "/document/center",
        "/document/center",
        6,
        icon="IconProBookOutlined",
    ),
    _page(
        "report-center",
        None,
        "报告中心",
        "/report/center",
        "/report/center",
        7,
        icon="IconProAnalysisOutlined",
    ),
    _page(
        "personnel-equipment",
        None,
        "人员设备",
        "/personnel/equipment",
        "/personnel/equipment",
        8,
        icon="IconProUserOutlined",
    ),
]


SYSTEM_SEED_MENUS = [
    _directory(
        "system-root",
        None,
        "系统设置",
        "/system",
        99,
        icon="IconProSettingOutlined",
        meta=_merge_meta(("系統設置", "System Settings")),
    ),
    _page(
        "system-user",
        "system-root",
        "用户管理",
        "/system/user",
        "/system/user",
        1,
        icon="IconProUserOutlined",
        meta=_merge_meta(("用戶管理", "User")),
    ),
    _button("system-user-query", "system-user", "查询用户", "sys:user:list", 1),
    _button("system-user-add", "system-user", "新增用户", "system:user:add", 101),
    _button("system-user-edit", "system-user", "修改用户", "system:user:edit", 102),
    _button("system-user-remove", "system-user", "删除用户", "system:user:remove", 103),
    _button("system-user-import", "system-user", "导入用户", "system:user:import", 104),
    _button(
        "system-user-reset-password",
        "system-user",
        "重置密码",
        "system:user:reset-password",
        105,
    ),
    _button("system-user-status", "system-user", "修改状态", "system:user:status", 106),
    _hidden_page(
        "system-user-detail",
        "system-user",
        "用户详情",
        "/system/user/details/:id",
        "/system/user/details",
        5,
        icon="IconProUserOutlined",
        meta=_merge_meta(("用戶詳情", "UserDetails"), active="/system/user"),
    ),
    _page(
        "system-role",
        "system-root",
        "角色管理",
        "/system/role",
        "/system/role",
        2,
        icon="IconProIdcardOutlined",
        meta=_merge_meta(("角色管理", "Role")),
    ),
    _button("system-role-query", "system-role", "查询角色", "sys:role:list", 1),
    _button("system-role-add", "system-role", "新增角色", "system:role:add", 101),
    _button("system-role-edit", "system-role", "修改角色", "system:role:edit", 102),
    _button("system-role-remove", "system-role", "删除角色", "system:role:remove", 103),
    _button("system-role-auth", "system-role", "分配权限", "system:role:auth", 104),
    _page(
        "system-menu",
        "system-root",
        "菜单管理",
        "/system/menu",
        "/system/menu",
        3,
        icon="IconProAppstoreOutlined",
        meta=_merge_meta(("選單管理", "Menu")),
    ),
    _button("system-menu-query", "system-menu", "查询菜单", "sys:menu:list", 1),
    _button("system-menu-add", "system-menu", "新增菜单", "system:menu:add", 101),
    _button("system-menu-edit", "system-menu", "修改菜单", "system:menu:edit", 102),
    _button("system-menu-remove", "system-menu", "删除菜单", "system:menu:remove", 103),
    _page(
        "system-organization",
        "system-root",
        "机构管理",
        "/system/organization",
        "/system/organization",
        4,
        icon="IconProCityOutlined",
        meta=_merge_meta(("機构管理", "Organization")),
    ),
    _button("system-organization-query", "system-organization", "查询机构", "sys:org:list", 1),
    _button(
        "system-organization-add",
        "system-organization",
        "新增机构",
        "system:organization:add",
        101,
    ),
    _button(
        "system-organization-edit",
        "system-organization",
        "修改机构",
        "system:organization:edit",
        102,
    ),
    _button(
        "system-organization-remove",
        "system-organization",
        "删除机构",
        "system:organization:remove",
        103,
    ),
    _page(
        "system-dictionary",
        "system-root",
        "字典管理",
        "/system/dictionary",
        "/system/dictionary",
        7,
        icon="IconProBookOutlined",
        meta=_merge_meta(("字典管理", "Dictionary"), hide_footer=True),
    ),
    _button("system-dictionary-query", "system-dictionary", "查询字典", "sys:dict:list", 1),
    _button(
        "system-dictionary-add",
        "system-dictionary",
        "新增字典",
        "system:dictionary:add",
        101,
    ),
    _button(
        "system-dictionary-edit",
        "system-dictionary",
        "修改字典",
        "system:dictionary:edit",
        102,
    ),
    _button(
        "system-dictionary-remove",
        "system-dictionary",
        "删除字典",
        "system:dictionary:remove",
        103,
    ),
    _button(
        "system-dictionary-data-add",
        "system-dictionary",
        "新增字典项",
        "system:dictionary-data:add",
        201,
    ),
    _button(
        "system-dictionary-data-edit",
        "system-dictionary",
        "修改字典项",
        "system:dictionary-data:edit",
        202,
    ),
    _button(
        "system-dictionary-data-remove",
        "system-dictionary",
        "删除字典项",
        "system:dictionary-data:remove",
        203,
    ),
    _page(
        "system-file",
        "system-root",
        "文件管理",
        "/system/file",
        "/system/file",
        8,
        icon="IconProFolderOutlined",
        meta=_merge_meta(("檔案管理", "File")),
    ),
    _button("system-file-query", "system-file", "查看记录", "sys:file:list", 1),
    _button("system-file-remove", "system-file", "删除文件", "system:file:remove", 101),
    _page(
        "system-login-record",
        "system-root",
        "登录日志",
        "/system/login-record",
        "/system/login-record",
        9,
        icon="IconProCalendarOutlined",
        authority="sys:login-record:list",
        meta=_merge_meta(("登入日誌", "LoginRecord")),
    ),
    _page(
        "system-operation-record",
        "system-root",
        "操作日志",
        "/system/operation-record",
        "/system/operation-record",
        10,
        icon="IconProLogOutlined",
        authority="sys:operation-record:list",
        meta=_merge_meta(("操作日誌", "OperationRecord")),
    ),
    _page(
        "system-audit-log",
        "system-root",
        "审计日志",
        "/system/audit-log",
        "/system/audit-log",
        11,
        icon="IconProProtectOutlined",
        authority="sys:audit-log:list",
        meta=_merge_meta(("審計日誌", "AuditLog")),
    ),
]


USER_SEED_MENUS = [
    _directory(
        "user-root",
        None,
        "个人中心",
        "/user",
        10,
        icon="IconProControlOutlined",
        meta=_merge_meta(("個人中心", "User")),
    ),
    _page(
        "user-profile",
        "user-root",
        "我的资料",
        "/user/profile",
        "/user/profile",
        1,
        icon="IconProUserOutlined",
        meta=_merge_meta(("個人資料", "Profile")),
    ),
    _button("user-profile-update", "user-profile", "保存资料", "user:profile:update", 101),
    _button("user-profile-password", "user-profile", "修改密码", "user:profile:password", 102),
    _page(
        "user-message",
        "user-root",
        "我的消息",
        "/user/message",
        "/user/message",
        2,
        icon="IconProMessageOutlined",
        meta=_merge_meta(("我的消息", "Message")),
    ),
    _button("user-message-status", "user-message", "处理消息", "user:message:status", 101),
    _button("user-message-remove", "user-message", "删除消息", "user:message:remove", 102),
]


EXTENSION_SEED_MENUS = [
    _directory(
        "extension-root",
        None,
        "扩展组件",
        "/extension",
        9,
        icon="IconProAppstoreAddOutlined",
        meta=_merge_meta(None, badge={"isDot": True}),
    ),
    _page("extension-table", "extension-root", "高级表格", "/extension/table", "/extension/table", 1, icon="IconProLinkOutlined"),
    _page("extension-modal", "extension-root", "高级弹窗", "/extension/modal", "/extension/modal", 2, icon="IconProLinkOutlined", meta=_merge_meta(None, badge={"isDot": True})),
    _page("extension-message", "extension-root", "消息提示", "/extension/message", "/extension/message", 3, icon="IconProLinkOutlined"),
    _page("extension-layout", "extension-root", "布局组件", "/extension/layout", "/extension/layout", 4, icon="IconProLinkOutlined"),
    _page("extension-table-select", "extension-root", "下拉表格", "/extension/table-select", "/extension/table-select", 5, icon="IconProLinkOutlined"),
    _page("extension-tree-select", "extension-root", "下拉树", "/extension/tree-select", "/extension/tree-select", 6, icon="IconProLinkOutlined"),
    _page("extension-upload", "extension-root", "文件上传", "/extension/upload", "/extension/upload", 7, icon="IconProLinkOutlined"),
    _page("extension-icon", "extension-root", "图标选择", "/extension/icon", "/extension/icon", 8, icon="IconProLinkOutlined"),
    _page("extension-file", "extension-root", "文件列表", "/extension/file", "/extension/file", 9, icon="IconProLinkOutlined"),
    _page("extension-split", "extension-root", "分割面板", "/extension/split", "/extension/split", 10, icon="IconProLinkOutlined", meta=_merge_meta(None, badge={"isDot": True})),
    _page("extension-printer", "extension-root", "打印组件", "/extension/printer", "/extension/printer", 11, icon="IconProLinkOutlined"),
    _page("extension-text", "extension-root", "文本组件", "/extension/text", "/extension/text", 12, icon="IconProLinkOutlined"),
    _page("extension-tag", "extension-root", "标签输入", "/extension/tag", "/extension/tag", 13, icon="IconProLinkOutlined"),
    _page("extension-avatar", "extension-root", "头像组合", "/extension/avatar", "/extension/avatar", 14, icon="IconProLinkOutlined"),
    _page("extension-tour", "extension-root", "引导组件", "/extension/tour", "/extension/tour", 15, icon="IconProLinkOutlined"),
    _page("extension-menu", "extension-root", "导航菜单", "/extension/menu", "/extension/menu", 16, icon="IconProLinkOutlined"),
    _page("extension-check-card", "extension-root", "可选卡片", "/extension/check-card", "/extension/check-card", 17, icon="IconProLinkOutlined"),
    _page("extension-watermark", "extension-root", "水印组件", "/extension/watermark", "/extension/watermark", 18, icon="IconProLinkOutlined"),
    _page("extension-viewer", "extension-root", "查看器", "/extension/viewer", "/extension/viewer", 19, icon="IconProLinkOutlined"),
    _page("extension-steps", "extension-root", "步骤条", "/extension/steps", "/extension/steps", 19, icon="IconProLinkOutlined"),
    _page("extension-segmented", "extension-root", "分段器", "/extension/segmented", "/extension/segmented", 20, icon="IconProLinkOutlined"),
    _page("extension-tabs", "extension-root", "标签页", "/extension/tabs", "/extension/tabs", 21, icon="IconProLinkOutlined"),
    _page("extension-qr-code", "extension-root", "二维码", "/extension/qr-code", "/extension/qr-code", 22, icon="IconProLinkOutlined"),
    _page("extension-bar-code", "extension-root", "条形码", "/extension/bar-code", "/extension/bar-code", 23, icon="IconProLinkOutlined"),
    _page("extension-regions", "extension-root", "城市选择", "/extension/regions", "/extension/regions", 24, icon="IconProLinkOutlined"),
    _page("extension-excel", "extension-root", "导入导出", "/extension/excel", "/extension/excel", 25, icon="IconProLinkOutlined"),
    _page("extension-dragsort", "extension-root", "拖拽排序", "/extension/dragsort", "/extension/dragsort", 26, icon="IconProLinkOutlined"),
    _page("extension-map", "extension-root", "地图组件", "/extension/map", "/extension/map", 27, icon="IconProLinkOutlined"),
    _page("extension-player", "extension-root", "视频播放", "/extension/player", "/extension/player", 28, icon="IconProLinkOutlined"),
    _page("extension-editor", "extension-root", "富文本框", "/extension/editor", "/extension/editor", 29, icon="IconProLinkOutlined"),
    _page("extension-markdown", "extension-root", "markdown", "/extension/markdown", "/extension/markdown", 30, icon="IconProLinkOutlined"),
    _page("extension-role-select", "extension-root", "角色选择", "/extension/role-select", "/extension/role-select", 31, icon="IconProLinkOutlined", meta=_merge_meta(None, badge={"isDot": True})),
    _page("extension-department-select", "extension-root", "部门选择", "/extension/department-select", "/extension/department-select", 31, icon="IconProLinkOutlined", meta=_merge_meta(None, badge={"isDot": True})),
    _page("extension-monaco", "extension-root", "代码编辑", "/extension/monaco", "/extension/monaco", 31, icon="IconProLinkOutlined"),
    _page("extension-user-select", "extension-root", "人员选择", "/extension/user-select", "/extension/user-select", 31, icon="IconProLinkOutlined", meta=_merge_meta(None, badge={"isDot": True})),
]


SEED_MENUS = [
    *DASHBOARD_SEED_MENUS,
    *BUSINESS_SEED_MENUS,
    *EXTENSION_SEED_MENUS,
    *USER_SEED_MENUS,
    *SYSTEM_SEED_MENUS,
]
